idf_component_register(
    SRCS 
        "main.cpp"
        "buttons.cpp"
        "eink/DEV_Config.cpp"
        "eink/display.cpp"
        "eink/EPD_2in9.c"
        "graphics/canvas.cpp"
        "graphics/drawing.cpp"
        "graphics/font.cpp"
    INCLUDE_DIRS
        "."
        "eink"
        "graphics"
    PRIV_REQUIRES
        esp_driver_gpio
        esp_driver_spi
)